# package management
library(rtweet)
library(glue)

# set up twitter auth
consumerKey <- Sys.getenv("TWITTER_APP_CONSUMER_KEY")
consumerSecret <- Sys.getenv("TWITTER_APP_CONSUMER_SECRET")
accessToken <- Sys.getenv("TWITTER_APP_ACCESS_TOKEN")
accessTokenSecret <- Sys.getenv("TWITTER_APP_ACCESS_TOKEN_SECRET")

token <- rtweet::rtweet_bot(
  api_key       = consumerKey,
  api_secret    = consumerSecret,
  access_token  = accessToken,
  access_secret = accessTokenSecret
)

# post
post <- glue("doing a tweete with code\n\n[-_-]generated by: a good / polite boy's twitter bot\n[-_-]using: R and GitHub Actions")

rtweet::post_tweet(
  status = post,
  token = token
)
