name: random_sentence_twitter_bot
on:
  schedule:
    - cron: '0 * * * *'



jobs:
  random_sentence_twitter_bot-post:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@v2
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install glue package
        run: Rscript -e 'install.packages("glue", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript random_sentence_generator.R
env:
            TWITTER_APP_CONSUMER_KEY: ${{ secrets.TWITTER_APP_CONSUMER_KEY }}
            TWITTER_APP_CONSUMER_SECRET: ${{ secrets.TWITTER_APP_CONSUMER_SECRET }}
            TWITTER_APP_ACCESS_TOKEN: ${{ secrets.TWITTER_APP_ACCESS_TOKEN }}
            TWITTER_APP_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_APP_ACCESS_TOKEN_SECRET }}