name: random_sentence_twitter_bot

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  random_sentence_twitter_bot-post:
    runs-on: windows-latest
    env:
      TWITTER_APP_CONSUMER_KEY: ${{ secrets.TWITTER_APP_CONSUMER_KEY }}
      TWITTER_APP_CONSUMER_SECRET: ${{ secrets.TWITTER_APP_CONSUMER_SECRET }}
      TWITTER_APP_ACCESS_TOKEN: ${{ secrets.TWITTER_APP_ACCESS_TOKEN }}
      TWITTER_APP_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_APP_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install Dependencies
        run: |
          install.packages("rtweet")
          install.packages("glue")
        shell: Rscript {0}
      - name: Create and post tweet
        run: Rscript './random_sentence_generator.R'